name: CI for Backend

on:
  push:
    branches: [ main ]
    paths:
      - Draw.it.Server/**
      - '!**.md'
  pull_request:
    branches: [ main ]
    paths:
      - Draw.it.Server/**
      - .github/workflows/**
      - '!**.md'

jobs:
  lint_format:
    name: ðŸ§¹ Lint and Format Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint and check formatting
        uses: ./.github/actions/dotnet-lint-format
        with:
          project_path: Draw.it.Server

  test_coverage:
    name: ðŸ§ª Test Backend with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests with coverage
        id: test_coverage
        uses: ./.github/actions/dotnet-test-coverage
        with:
          test_project_path: Draw.it.Server.Tests.Unit
      
      - name: Placeholder for uploading
        run: echo "Coverage report located at ${{ steps.test_coverage.outputs.coverage_output }}"
