name: CI for Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - draw.it.client/**
      - '!**.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - draw.it.client/**
      - '!**.md'

jobs:
  lint:
    name: ðŸ§¹ Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/node-lint
        with:
          project_path: 'draw.it.client'
